/*
 * Copyright 2026 Jim Voris.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.qumasoft.guitools.qwin.dialog;

import com.qumasoft.guitools.qwin.QWinFrame;
import com.qumasoft.guitools.qwin.operation.OperationApplyLabel;
import com.qumasoft.qvcslib.CommonLabel;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jim Voris.
 */
public class ApplyLabelDialog extends AbstractQWinCommandDialog {
    private final OperationApplyLabel applyLabelOperation;
    private CommonLabel selectedLabel;

    /**
     * Creates new form ApplyLabelDialog.
     * @param parent QWinFrame
     * @param operation the apply label operation.
     */
    public ApplyLabelDialog(QWinFrame parent, OperationApplyLabel operation) {
        super(parent, true);
        applyLabelOperation = operation;
        initComponents();
        populateComponents(parent);
    }

    private void populateComponents(QWinFrame parent) {
        List<CommonLabel> currentLabels = parent.getLabelsList();
        LabelsListModel model = new LabelsListModel();
        model.populateModel(currentLabels);
        labelList.setModel(model);
    }

    private void closeDialog(Object object) {
        setVisible(false);
        dispose();
    }

    @Override
    public void dismissDialog() {
        cancelButtonActionPerformed(null);
    }

    private boolean validateData() {
        boolean retVal = false;
        selectedLabel = (CommonLabel) labelList.getSelectedValue();
        String labelText = selectedLabel.getLabelText();
        if (labelText.length() > 0) {
            retVal = true;
        }
        return retVal;
    }

    static class LabelsListModel extends DefaultListModel<CommonLabel> {
        private static final long serialVersionUID = 1L;

        void populateModel(List<CommonLabel> lblList) {
            // Populate the list of labels...
            for (CommonLabel label : lblList) {
                addElement(label);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseLabelToApplyLabel = new javax.swing.JLabel();
        labelListScrollPane = new javax.swing.JScrollPane();
        labelList = new javax.swing.JList<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Apply Label");

        chooseLabelToApplyLabel.setFont(new java.awt.Font("Arial", 0, 12));
        chooseLabelToApplyLabel.setText("Choose Label to Apply:");

        labelList.setFont(new java.awt.Font("Arial", 0, 12));
        labelList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        labelListScrollPane.setViewportView(labelList);

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseLabelToApplyLabel)
                            .addComponent(labelListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseLabelToApplyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (validateData()) {
            closeDialog(null);
            applyLabelOperation.processDialogResult(selectedLabel);
        } else {
            JOptionPane.showMessageDialog(QWinFrame.getQWinFrame(), "The label cannot be blank.", "Label String Required", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel chooseLabelToApplyLabel;
    private javax.swing.JList<CommonLabel> labelList;
    private javax.swing.JScrollPane labelListScrollPane;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
