/*
 * Copyright 2026 Jim Voris.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.qumasoft.guitools.qwin.dialog;

import com.qumasoft.guitools.qwin.QWinFrame;
import com.qumasoft.guitools.qwin.operation.OperationDeleteLabel;
import com.qumasoft.qvcslib.CommonLabel;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jim Voris.
 */
public class DeleteLabelDialog extends AbstractQWinCommandDialog {
    private final OperationDeleteLabel deleteLabelOperation;
    private String labelText;
    private final List<CommonLabel> existingLabelList;

    /**
     * Creates new form DeleteLabelDialog.
     * @param qWin QWin frame.
     * @param operation the delete label operation.
     * @param modal is this a modal dialog.
     */
    public DeleteLabelDialog(QWinFrame qWin, OperationDeleteLabel operation, boolean modal) {
        super(qWin, modal);
        deleteLabelOperation = operation;
        existingLabelList = qWin.getLabelsList();
        initComponents();
        populateComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        existingLablesLabel = new javax.swing.JLabel();
        existingLabelsScrollPane = new javax.swing.JScrollPane();
        existingLabelsList = new javax.swing.JList<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Label");
        setResizable(false);

        existingLablesLabel.setText("Existing Labels:");

        existingLabelsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        existingLabelsScrollPane.setViewportView(existingLabelsList);

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(existingLablesLabel)
                            .addComponent(existingLabelsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(existingLablesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existingLabelsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (validateData()) {
            closeDialog(null);
            deleteLabelOperation.processDialogResult(labelText);
        } else {
            JOptionPane.showMessageDialog(QWinFrame.getQWinFrame(), "The label cannot be blank.", "Label String Required", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void populateComponents() {
        LabelsListModel model = new LabelsListModel();
        model.populateModel(existingLabelList);
        existingLabelsList.setModel(model);
    }

    private void closeDialog(Object object) {
        setVisible(false);
        dispose();
    }

    @Override
    public void dismissDialog() {
        cancelButtonActionPerformed(null);
    }

    private boolean validateData() {
        boolean retVal = false;
        CommonLabel commonLabel = (CommonLabel) existingLabelsList.getSelectedValue();
        labelText = commonLabel.getLabelText();
        if (labelText.length() > 0) {
            retVal = true;
        }
        return retVal;
    }

    static class LabelsListModel extends DefaultListModel<CommonLabel> {
        private static final long serialVersionUID = 1L;

        void populateModel(List<CommonLabel> labelList) {
            // Populate the list of labels...
            for (CommonLabel label : labelList) {
                addElement(label);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JList<CommonLabel> existingLabelsList;
    private javax.swing.JScrollPane existingLabelsScrollPane;
    private javax.swing.JLabel existingLablesLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
